/*
  Rubén Hermidio Fernández Segura

  Se trata de un software que registre pacientes de un centro de salud en la opción 1,
  en la opción 2 se muestran todos los pacientes registrados y en la opción 3
  se puede buscar un paciente especifico por id y si exite en la lista enlazada se le permite 
  al usuario modificar los datos y volver a guardar.
 */
package Vistas;

import ClasesLogicas.Metodos;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ClasesLogicas.Persona;

/**
 *
 * @author Fernández
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private CardLayout cardLayout; 
    private int id;
        
    private Metodos metodos = new Metodos();
     
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Image icono = new ImageIcon( getClass().getResource("/Imagenes/Logo.png") ).getImage(); 
        setIconImage(icono);

        btnAgregar1.setFocusable(false);
        btnMostrar.setFocusable(false);
        btnBuscarEditar.setFocusable(false);
        btnSalir.setFocusable(false);
        btnCancelar.setFocusable(false);
        OcultarMostrarCampos(false);

        cardLayout = (CardLayout)(pnlCardLayout.getLayout());
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
        
        id = 1;
        lblTitulo.setText("Bienvenid@");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JButton();
        btnBuscarEditar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        pnlCardLayout = new javax.swing.JPanel();
        pnlBienvenida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlAgregarPersona = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbxNacionalidad = new javax.swing.JComboBox<>();
        txtEdad = new javax.swing.JTextField();
        chxCovid = new javax.swing.JCheckBox();
        chxVacunacion = new javax.swing.JCheckBox();
        btnAgregar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnVolverAgregar = new javax.swing.JButton();
        btnCancelarAgregar = new javax.swing.JButton();
        pnlMostrarPersonas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnVolverMostrar = new javax.swing.JButton();
        pnlBuscarEditar = new javax.swing.JPanel();
        lblBuscarEditar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblNacionalidad = new javax.swing.JLabel();
        cbxNacionalidadEditar = new javax.swing.JComboBox<>();
        lblNombreEditar = new javax.swing.JLabel();
        txtNombreEditar = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdadEditar = new javax.swing.JTextField();
        lblCovid = new javax.swing.JLabel();
        lblVacuna = new javax.swing.JLabel();
        chxCovidEditar = new javax.swing.JCheckBox();
        chxVacunacionEditar = new javax.swing.JCheckBox();
        txtID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVolverEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centro de Salud");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));

        btnAgregar1.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregar1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AddPerson.png"))); // NOI18N
        btnAgregar1.setText("Agregar Persona");
        btnAgregar1.setToolTipText("");
        btnAgregar1.setBorder(null);
        btnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgregar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar1.setIconTextGap(15);
        btnAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseClicked(evt);
            }
        });
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnBuscarEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscarEditar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBuscarEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarEditar.png"))); // NOI18N
        btnBuscarEditar.setText("Buscar y Editar");
        btnBuscarEditar.setToolTipText("");
        btnBuscarEditar.setBorder(null);
        btnBuscarEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscarEditar.setIconTextGap(15);
        btnBuscarEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarEditarMouseClicked(evt);
            }
        });
        btnBuscarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEditarActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(51, 51, 51));
        btnMostrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VerLista.png"))); // NOI18N
        btnMostrar.setText("Mostrar Personas");
        btnMostrar.setToolTipText("");
        btnMostrar.setBorder(null);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMostrar.setIconTextGap(15);
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
        });
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        jLabel2.setText("Menú");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setIconTextGap(15);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.setIconTextGap(15);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
            .addComponent(btnBuscarEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pnlCardLayout.setBackground(new java.awt.Color(102, 102, 102));
        pnlCardLayout.setLayout(new java.awt.CardLayout());

        pnlBienvenida.setBackground(new java.awt.Color(51, 51, 51));
        pnlBienvenida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlBienvenida.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenidos al Centro de Salud");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBienvenidaLayout = new javax.swing.GroupLayout(pnlBienvenida);
        pnlBienvenida.setLayout(pnlBienvenidaLayout);
        pnlBienvenidaLayout.setHorizontalGroup(
            pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        pnlBienvenidaLayout.setVerticalGroup(
            pnlBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBienvenidaLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        pnlCardLayout.add(pnlBienvenida, "pnlBienvenida");

        pnlAgregarPersona.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese los datos de la persona que desea ingresar");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nacionalidad");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Esquema completo de vacunación COVID 19");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edad");
        jLabel8.setPreferredSize(new java.awt.Dimension(32, 19));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vacuna de Influenza");

        lblID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("NULL");

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));

        cbxNacionalidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxNacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        cbxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Nacionalidad", "Costarricense", "Extranjero" }));

        txtEdad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));

        chxCovid.setBackground(new java.awt.Color(51, 51, 51));
        chxCovid.setForeground(new java.awt.Color(255, 255, 255));

        chxVacunacion.setBackground(new java.awt.Color(51, 51, 51));
        chxVacunacion.setForeground(new java.awt.Color(255, 255, 255));

        btnAgregar2.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregar2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregar2.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AddPerson.png"))); // NOI18N
        btnAgregar2.setText("Agregar Persona");
        btnAgregar2.setToolTipText("");
        btnAgregar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgregar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar2.setIconTextGap(10);
        btnAgregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar2MouseExited(evt);
            }
        });
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        btnVolverAgregar.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVolverAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btnVolverAgregar.setText("Volver");
        btnVolverAgregar.setToolTipText("");
        btnVolverAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnVolverAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnVolverAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolverAgregar.setIconTextGap(10);
        btnVolverAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverAgregarMouseExited(evt);
            }
        });
        btnVolverAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAgregarActionPerformed(evt);
            }
        });

        btnCancelarAgregar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelarAgregar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelarAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar1.png"))); // NOI18N
        btnCancelarAgregar.setText("Cancelar");
        btnCancelarAgregar.setToolTipText("");
        btnCancelarAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnCancelarAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCancelarAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelarAgregar.setIconTextGap(10);
        btnCancelarAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarAgregarMouseExited(evt);
            }
        });
        btnCancelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarPersonaLayout = new javax.swing.GroupLayout(pnlAgregarPersona);
        pnlAgregarPersona.setLayout(pnlAgregarPersonaLayout);
        pnlAgregarPersonaLayout.setHorizontalGroup(
            pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chxCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chxVacunacion))
                            .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarPersonaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        pnlAgregarPersonaLayout.setVerticalGroup(
            pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarPersonaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chxCovid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chxVacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(pnlAgregarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar2)
                    .addComponent(btnCancelarAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(btnVolverAgregar)
                .addGap(22, 22, 22))
        );

        pnlCardLayout.add(pnlAgregarPersona, "pnlAgregarPersona");

        pnlMostrarPersonas.setBackground(new java.awt.Color(51, 51, 51));

        tblPersonas.setBackground(new java.awt.Color(255, 255, 255));
        tblPersonas.setForeground(new java.awt.Color(0, 0, 0));
        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Nacionalidad", "Edad", "Esquema Covid", "Vacuna Influenza"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonas.setGridColor(new java.awt.Color(0, 0, 0));
        tblPersonas.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tblPersonas.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tblPersonas);
        if (tblPersonas.getColumnModel().getColumnCount() > 0) {
            tblPersonas.getColumnModel().getColumn(0).setResizable(false);
            tblPersonas.getColumnModel().getColumn(1).setResizable(false);
            tblPersonas.getColumnModel().getColumn(2).setResizable(false);
            tblPersonas.getColumnModel().getColumn(3).setResizable(false);
            tblPersonas.getColumnModel().getColumn(4).setResizable(false);
            tblPersonas.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lista de Personas");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVolverMostrar.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverMostrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVolverMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btnVolverMostrar.setText("Volver");
        btnVolverMostrar.setToolTipText("");
        btnVolverMostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnVolverMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverMostrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnVolverMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolverMostrar.setIconTextGap(10);
        btnVolverMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMostrarMouseExited(evt);
            }
        });
        btnVolverMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMostrarPersonasLayout = new javax.swing.GroupLayout(pnlMostrarPersonas);
        pnlMostrarPersonas.setLayout(pnlMostrarPersonasLayout);
        pnlMostrarPersonasLayout.setHorizontalGroup(
            pnlMostrarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMostrarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                    .addGroup(pnlMostrarPersonasLayout.createSequentialGroup()
                        .addComponent(btnVolverMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMostrarPersonasLayout.setVerticalGroup(
            pnlMostrarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMostrarPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVolverMostrar)
                .addGap(21, 21, 21))
        );

        pnlCardLayout.add(pnlMostrarPersonas, "pnlMostrarPersonas");

        pnlBuscarEditar.setBackground(new java.awt.Color(51, 51, 51));

        lblBuscarEditar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBuscarEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarEditar.setText("Ingrese el ID de la persona que desea buscar");
        lblBuscarEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");

        lblNacionalidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        lblNacionalidad.setText("Nacionalidad");

        cbxNacionalidadEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxNacionalidadEditar.setForeground(new java.awt.Color(0, 0, 0));
        cbxNacionalidadEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Nacionalidad", "Costarricense", "Extranjero" }));

        lblNombreEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEditar.setText("Nombre");

        txtNombreEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombreEditar.setForeground(new java.awt.Color(0, 0, 0));

        lblEdad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(255, 255, 255));
        lblEdad.setText("Edad");
        lblEdad.setPreferredSize(new java.awt.Dimension(32, 19));

        txtEdadEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEdadEditar.setForeground(new java.awt.Color(0, 0, 0));

        lblCovid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCovid.setForeground(new java.awt.Color(255, 255, 255));
        lblCovid.setText("Esquema completo de vacunación COVID 19");

        lblVacuna.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVacuna.setForeground(new java.awt.Color(255, 255, 255));
        lblVacuna.setText("Vacuna de Influenza");

        chxCovidEditar.setBackground(new java.awt.Color(51, 51, 51));
        chxCovidEditar.setForeground(new java.awt.Color(255, 255, 255));

        chxVacunacionEditar.setBackground(new java.awt.Color(51, 51, 51));
        chxVacunacionEditar.setForeground(new java.awt.Color(255, 255, 255));

        txtID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.setActionCommand("Buscar     ");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscar.setIconTextGap(10);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardar.setIconTextGap(10);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolverEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverEditar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVolverEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btnVolverEditar.setText("Volver");
        btnVolverEditar.setToolTipText("");
        btnVolverEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnVolverEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnVolverEditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolverEditar.setIconTextGap(10);
        btnVolverEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverEditarMouseExited(evt);
            }
        });
        btnVolverEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEditarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.setIconTextGap(10);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarEditarLayout = new javax.swing.GroupLayout(pnlBuscarEditar);
        pnlBuscarEditar.setLayout(pnlBuscarEditarLayout);
        pnlBuscarEditarLayout.setHorizontalGroup(
            pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarEditarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarEditarLayout.createSequentialGroup()
                                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                                        .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreEditar)
                                            .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                                                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                                                        .addComponent(cbxNacionalidadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtEdadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarEditarLayout.createSequentialGroup()
                                        .addComponent(lblCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chxCovidEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(chxVacunacionEditar)))
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarEditarLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(395, 395, 395))))
                    .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                        .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                                .addComponent(btnVolverEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblBuscarEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlBuscarEditarLayout.setVerticalGroup(
            pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(49, 49, 49)
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNacionalidadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chxCovidEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chxVacunacionEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(pnlBuscarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btnVolverEditar)
                .addGap(21, 21, 21))
        );

        pnlCardLayout.add(pnlBuscarEditar, "pnlBuscarEditar");

        pnlTitulo.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 102, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agregar Personas");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Para ocultar o Mostrar los campos cuando se busca
    public void OcultarMostrarCampos(boolean estado){
        txtID.setEditable(!estado);
        lblNombreEditar.setVisible(estado);
        txtNombreEditar.setVisible(estado);
        lblNacionalidad.setVisible(estado);
        cbxNacionalidadEditar.setVisible(estado);
        lblEdad.setVisible(estado);
        txtEdadEditar.setVisible(estado);
        lblCovid.setVisible(estado);
        chxCovidEditar.setVisible(estado);
        lblVacuna.setVisible(estado);
        chxVacunacionEditar.setVisible(estado);
        btnBuscar.setEnabled(!estado);
        btnGuardar.setVisible(estado);
        btnCancelar.setVisible(estado);
    }
   
    //Método que limpia los campos para agregar una persona nueva
    public void LimpiarCampos(){
        txtNombre.setText("");
        cbxNacionalidad.setSelectedIndex(0);
        txtEdad.setText("");
        chxCovid.setSelected(false);
        chxVacunacion.setSelected(false);
    }

    //Método que carga los datos para ser editados
    private void CargarDatosParaEditar(Persona persona) {
        txtNombreEditar.setText(persona.getNombre());
        cbxNacionalidadEditar.setSelectedItem(persona.getNacionalidad());
        txtEdadEditar.setText(String.valueOf(persona.getEdad()));
        chxCovidEditar.setSelected(persona.isVacunacionCovid19());
        chxVacunacionEditar.setSelected(persona.isVacunaInflueza());
    }
    
    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        lblTitulo.setText("Agregar Personas");
        cardLayout.show(pnlCardLayout, "pnlAgregarPersona");
        lblID.setText(String.valueOf(id));  
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(metodos.ObtenerLista().isEmpty()){
            JOptionPane.showConfirmDialog(null, "No hay personas agregadas", "Mostrar Personas",-1,0);
        }else{
            cardLayout.show(pnlCardLayout, "pnlMostrarPersonas");
            metodos.MostrarPersonas(tblPersonas);
            lblTitulo.setText("Mostrar Personas");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEditarActionPerformed
        if(metodos.ObtenerLista().isEmpty()){
            JOptionPane.showConfirmDialog(null, "No hay personas agregadas", "Buscar y Editar Personas",-1,0);
        }else{
            lblTitulo.setText("Buscar Personas");
            lblBuscarEditar.setText("Ingrese el ID de la persona que desea buscar");
            cardLayout.show(pnlCardLayout, "pnlBuscarEditar");
        }
    }//GEN-LAST:event_btnBuscarEditarActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        //Si la información ingresada es correcta se agrega la nueva persona a la lista
        if(metodos.ValidarNombre(txtNombre.getText()) && metodos.ValidarNacionalidad(String.valueOf(cbxNacionalidad.getSelectedItem())) && metodos.ValidarEdad(txtEdad.getText().trim())){
            Persona nueva = new Persona(Integer.parseInt(lblID.getText()), txtNombre.getText(), cbxNacionalidad.getSelectedItem().toString(),
                    Integer.parseInt(txtEdad.getText()), chxCovid.isSelected(), chxVacunacion.isSelected());

            if (JOptionPane.showConfirmDialog(null, "Persona ingresada exitosamente.\nDesea ingresar otra persona?", "Agregar Personas",0,1)
                    == JOptionPane.YES_OPTION){
                lblID.setText(String.valueOf(++id));
            }else{
                lblTitulo.setText("Bienvenid@");
                cardLayout.show(pnlCardLayout, "pnlBienvenida");
                id++;
            }
            metodos.AgregarPersonas(nueva);
            LimpiarCampos();
        }      
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        LinkedList<Persona> listaPersonas = metodos.ObtenerLista();
        Iterator<Persona> itr = listaPersonas.iterator();
        
        if (!txtID.getText().isEmpty()) {
            Persona personaBuscada = metodos.Buscar(listaPersonas, itr, Integer.parseInt(txtID.getText().trim()));
                         
            if(personaBuscada != null){
                OcultarMostrarCampos(true);
                CargarDatosParaEditar(personaBuscada);
                lblTitulo.setText("Editar Personas");
                lblBuscarEditar.setText("Ingrese los datos que desea modificar");
            }
            else{
                JOptionPane.showConfirmDialog(null, "El ID: " + txtID.getText() + " no se encuentra", "Buscar Personas",-1,0);
                txtID.setText("");
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Debe ingresar un ID", "Buscar Personas",-1,0);
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(metodos.Guardar(Integer.parseInt(txtID.getText()),txtNombreEditar.getText(),txtEdadEditar.getText().trim(),
                String.valueOf(cbxNacionalidadEditar.getSelectedItem()),chxCovidEditar.isSelected(),chxVacunacionEditar.isSelected())){
            
            if (JOptionPane.showConfirmDialog(null, "Persona modificada correctamente.\nDesea modificar otra?", "Editar Personas", 0, 1)
                    == JOptionPane.YES_OPTION) {
                LimpiarCampos();
                lblTitulo.setText("Buscar Personas");
                lblBuscarEditar.setText("Ingrese el ID de la persona que desea buscar");
            } else {
                lblTitulo.setText("Bienvenid@");
                cardLayout.show(pnlCardLayout, "pnlBienvenida");
            }
            OcultarMostrarCampos(false); 
        }
        txtID.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMostrarActionPerformed
        lblTitulo.setText("Bienvenid@");
        btnMostrar.setBackground(new Color(51,51,51));
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
    }//GEN-LAST:event_btnVolverMostrarActionPerformed

    private void btnVolverEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEditarActionPerformed
        lblTitulo.setText("Bienvenid@");
        btnBuscarEditar.setBackground(new Color(51,51,51));
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
        OcultarMostrarCampos(false);
        txtID.setText("");
    }//GEN-LAST:event_btnVolverEditarActionPerformed

    private void btnVolverAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAgregarActionPerformed
        lblTitulo.setText("Bienvenid@");
        btnAgregar1.setBackground(new Color(51,51,51));
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
    }//GEN-LAST:event_btnVolverAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (JOptionPane.showConfirmDialog( null, "Está seguro que desea salir?","Salir",0,2) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseClicked
        btnAgregar1.setBackground(new Color(255,102,0));
        btnMostrar.setBackground(new Color(51,51,51));
        btnBuscarEditar.setBackground(new Color(51,51,51));         
    }//GEN-LAST:event_btnAgregar1MouseClicked

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        btnMostrar.setBackground(new Color(255,102,0));
        btnAgregar1.setBackground(new Color(51,51,51));
        btnBuscarEditar.setBackground(new Color(51,51,51)); 
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void btnBuscarEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEditarMouseClicked
        btnMostrar.setBackground(new Color(51,51,51));
        btnAgregar1.setBackground(new Color(51,51,51));
        btnBuscarEditar.setBackground(new Color(255,102,0));       
    }//GEN-LAST:event_btnBuscarEditarMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        lblTitulo.setText("Bienvenid@");
        btnBuscarEditar.setBackground(new Color(51,51,51));
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
        OcultarMostrarCampos(false);
        txtID.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAgregarActionPerformed
        lblTitulo.setText("Bienvenid@");
        btnAgregar1.setBackground(new Color(51,51,51));
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
    }//GEN-LAST:event_btnCancelarAgregarActionPerformed

    private void btnAgregar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar2MouseEntered
        btnAgregar2.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnAgregar2MouseEntered

    private void btnAgregar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar2MouseExited
        btnAgregar2.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnAgregar2MouseExited

    private void btnCancelarAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAgregarMouseEntered
        btnCancelarAgregar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnCancelarAgregarMouseEntered

    private void btnCancelarAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAgregarMouseExited
        btnCancelarAgregar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnCancelarAgregarMouseExited

    private void btnVolverAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAgregarMouseEntered
        btnVolverAgregar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnVolverAgregarMouseEntered

    private void btnVolverAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAgregarMouseExited
        btnVolverAgregar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnVolverAgregarMouseExited

    private void btnVolverMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMostrarMouseEntered
         btnVolverMostrar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnVolverMostrarMouseEntered

    private void btnVolverMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMostrarMouseExited
        btnVolverMostrar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnVolverMostrarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnVolverEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverEditarMouseEntered
        btnVolverEditar.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnVolverEditarMouseEntered

    private void btnVolverEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverEditarMouseExited
        btnVolverEditar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_btnVolverEditarMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cardLayout.show(pnlCardLayout, "pnlBienvenida");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEditar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolverAgregar;
    private javax.swing.JButton btnVolverEditar;
    private javax.swing.JButton btnVolverMostrar;
    private javax.swing.JComboBox<String> cbxNacionalidad;
    private javax.swing.JComboBox<String> cbxNacionalidadEditar;
    private javax.swing.JCheckBox chxCovid;
    private javax.swing.JCheckBox chxCovidEditar;
    private javax.swing.JCheckBox chxVacunacion;
    private javax.swing.JCheckBox chxVacunacionEditar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarEditar;
    private javax.swing.JLabel lblCovid;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEditar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVacuna;
    private javax.swing.JPanel pnlAgregarPersona;
    private javax.swing.JPanel pnlBienvenida;
    private javax.swing.JPanel pnlBuscarEditar;
    private javax.swing.JPanel pnlCardLayout;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMostrarPersonas;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdadEditar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEditar;
    // End of variables declaration//GEN-END:variables
}
